### ISSUE TITLE
Multi Lingual Menu Items

### ISSUE THREAD

**Issue by jdalsem** [ColdTrick/menu_builder#1]
The label/title should come from a language file

**Comment by dote78** [comment]
Have you seen this modification in elgg plugin repository? Probably yes
https://elgg.org/plugins/1226896

**Comment by jdalsem** [comment]
This is already fixed in the 1.8 branch of this plugin https://github.com/ColdTrick/menu_builder/commit/9792f5b81dd7cccf62379f4555f7934066b155d1 It still needs to find its way to the master repo. Thanks for letting me know.

**Comment by dote78** [comment]
Nice. I hope you somehow have some time to bring it to the master repo. Including that option myself is far from what I can do in PHP. Thanks for your good work!!

**Comment by dote78** [comment]
Posted workaround in the community, in case someone reaches here looking for a solution. Keep the good work Jeroem!

https://elgg.org/discussion/view/2367520/allow-elgg-echo-in-menus

**Comment by jdalsem** [comment]
not going to happen
