### ISSUE TITLE
naming of id attributes is invalid if begun with a numeric character

### ISSUE THREAD

**Issue by propertunist** [ColdTrick/menu_builder#13]
while validating my site at: http://validator.w3.org/

i found that the use of numerics to begin id values is classed as an error there:

Line 155, Column 167: value of attribute "id" invalid: "5" cannot start a name
…="http://www.infiniteeureka.com/" id="5494">home</a></li><li class="elgg-menu-…
✉
It is possible that you violated the naming convention for this attribute. For example, id and name attributes must begin with a letter, not a digit.

so this affects all menu items created via menu_builder

**Comment by jdalsem** [comment]
In the current master the id attribute is no longer used on menu items
