### ISSUE TITLE
Deprecation message in 1.10

### ISSUE THREAD

**Issue by dote78** [ColdTrick/menu_builder#22]
When running this build in elgg 1.10 it throws the following message even tho it's working correctly:

"Deprecated in 1.10: use of .elgg-requires-confirmation is deprecated by data-confirm"

Doing a grep, the string is found in:

menu_builder/views/default/admin/appearance/menu_items.php:     $delete_menu_form_body .= elgg_view("input/submit", array("value" => elgg_echo("delete"), "class" => "elgg-requires-confirmation mtm elgg-button-submit"));

**Comment by jdalsem** [comment]
A deprecated notice is not a problem for the functionality of a plugin. It will only inform admins that a feature uses deprecated functionality at that eventually the old functionality will be removed from Elgg, so the plugin needs to update eventually. Removal of deprecated functionality will only happen in major releases.

**Comment by dote78** [comment]
Ok, thanks!!!

 

De: Jeroen Dalsem [mailto:notifications@github.com] 
Enviado el: martes, 24 de marzo de 2015 9:25
Para: ColdTrick/menu_builder
CC: dote78
Asunto: Re: [menu_builder] Deprecation message in 1.10 (#22)

 

A deprecated notice is not a problem for the functionality of a plugin. It will only inform admins that a feature uses deprecated functionality at that eventually the old functionality will be removed from Elgg, so the plugin needs to update eventually. Removal of deprecated functionality will only happen in major releases.
